app_about/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_about'
urlpatterns = [
    path('', views.index, name='index'),
    path('en/', views.index_en, name='index_en'),



]

app_auth/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_auth'
urlpatterns = [
    # path('', include('django.contrib.auth.urls'), name='login'),
    path('', views.login_user, name='login'),
    path('en/', views.login_user_en, name='login_en'),
    path('multilogin/<pk>', views.multilogin, name='multilogin'),
    path('logout/', views.logout_user, name='logout'),

    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path('reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('demo/', views.demo, name='demo'),
    path('demo_eng/', views.demo_eng, name='demo_eng'),

]

app_signup/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_signup'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('en/', views.signup_en, name='signup_en'),
    path('modal-help/', views.modal_help, name='modal_help'),



]

fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app_about.urls')),
    path('app/', include('app_frontend.urls')),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

app_about/models.py
from django.db import models

# Create your models here.

app_about/views.py
from django.shortcuts import render
import logging

logger = logging.getLogger(__name__)

def index(request):
    context = {}
    return render(request, 'app_about/index.html', context)

def index_en(request):
    context = {}
    return render(request, 'app_about/index_en.html', context)

app_about/templates/app_about/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google" value="notranslate"/>
        <title>FinS | Financial CRM</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.4.1/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type=image/x-icon>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div  class="d-flex flex-column justify-content-center align-items-center">
                        <div class="lang-container">
                            <a href="{% url 'app_about:index' %}"><span class="btn-lang active">РУ</span></a>
                            <a href="{% url 'app_about:index_en' %}"><span class="btn-lang ml-2">EN</span></a>
                        </div>
                        <a href="{% url 'app_about:index' %}"><img width='170px' src="{% static 'img/finslogo.svg' %}"></a>
                        <h2 class="text-center ">
                            Финансовый учет для студий и агентств.
                        </h2>
                        <p  class="text-center text-secondary">
                            Детальный учет финансовых показателей проектов, юнит-экономика, учет объемы выпоненных услуг.
                        </p>
                        <div class="btn-group">
                        <a href="{% url 'app_auth:demo' %}" class="btn btn-primary rounded-top w-100 pr-3 pl-3 pt-3 pb-3" role="button">Демо</a>
                        </div>
                        <div class="btn-group">
                            <a href="{% url 'app_auth:login' %}" class="btn btn-outline-primary rounded-left  pr-3 pl-3 pt-3 pb-3" role="button">Войти</a>
                            <a href="{% url 'app_signup:signup' %}" class="btn btn-outline-primary rounded-right pr-3 pl34 pt-3 pb-3" role="button">Зарегистрироваться</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

app_about/templates/app_about/index_en.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google" value="notranslate"/>
        <title>FinS | Financial CRM</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.4.1/dist/css/bootstrap.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type=image/x-icon>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div  class="d-flex flex-column justify-content-center align-items-center">
                        <div class="lang-container">
                            <a href="{% url 'app_about:index' %}"><span class="btn-lang ">РУ</span></a>
                            <a href="{% url 'app_about:index_en' %}"><span class="btn-lang active ml-2">EN</span></a>
                        </div>
                        <a href="{% url 'app_about:index' %}"><img width='170px' src="{% static 'img/finslogo.svg' %}"></a>
                        <h2 class="text-center ">
                            Financial CRM for agencies and web-studios.
                        </h2>
                        <p  class="text-center text-secondary">
                            Project financial details, unit-economy, reports  and much more.
                        </p>
                        <div class="btn-group">
                        <a href="{% url 'app_auth:demo_eng' %}" onclick=" setlang()" class="btn btn-primary  w-100 pr-3 pl-3 pt-3 pb-3" role="button">Demo</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    <script>
function setlang()
{
     console.log('a')
    sessionStorage.setItem('test', 1);
}
</script>

    </body>
</html>