app_about/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_about'
urlpatterns = [
    path('', views.index, name='index'),
    path('en/', views.index_en, name='index_en'),



]

app_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_project'
urlpatterns = [
    # path('', views.index, name='index'),
    # path('project/<pk>/', views.project, name='project'),
    path('api/', views.project_list),
    path('api/<int:pk>/', views.project_detail),
    path('api/extra/', views.project_extra),
    path('api/statistics/<int:pk>/', views.project_statistics),
    path('api/history/', views.project_history),
    path('api/excel/', views.excel_export),

    path('api/team_list/<int:pk>/', views.project_team_list),
    path('api/team/<int:pk>/', views.project_team_detail),

    path('api/service_list/<int:pk>/', views.project_service_list),
    path('api/service/<int:pk>/', views.project_service_detail),

    path('api/period_list/<int:pk>/', views.project_period_list),
    path('api/period/<int:pk>/', views.project_period_detail),

    path('api/report_list/<int:pk>/', views.project_report_list),
    path('api/report/<int:pk>/', views.project_report_detail),





    # path('project/<pk>/', views.project, name='project'),
    # path('project_create/', views.project_create, name='project_create'),
    # path('project_update/<pk>/', views.project_update, name='project_update'),
    # path('project_update_estimation/<pk>/', views.project_update_estimation, name='project_update_estimation'),
    # path('project_delete/<pk>/', views.project_delete, name='project_delete'),
    #
    # path('project/history', views.project_history, name='project_history'),
    #
    # path('ajax/load-subcat/', views.load_subcat, name='ajax_load_subcat'),
    #
    # path('create_period/<projectpk>/', views.create_period, name='create_period'),
    # path('update_period/<pk>/', views.update_period, name='update_period'),
    # path('delete_period/<pk>/', views.delete_period, name='delete_period'),
    #
    # path('service_create/<projectpk>/', views.service_create, name='service_create'),
    # path('service_update/<pk>/', views.service_update, name='service_update'),
    # path('service_delete/<pk>/', views.service_delete, name='service_delete'),
    #
    # path('report_create/<projectpk>/<periodpk>', views.report_create, name='report_create'),
    # path('report_update/<pk>/<projectpk>', views.report_update, name='report_update'),
    # path('report_delete/<pk>/', views.report_delete, name='report_delete'),
    #
    # path('team_create/<projectpk>/', views.team_create, name='team_create'),
    # path('team_update/<pk>/', views.team_update, name='team_update'),
    # path('team_delete/<pk>/', views.team_delete, name='team_delete'),
    #
    # path('excel_export/', views.excel_export, name='excel_export'),

]

app_transaction/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'app_transaction'
urlpatterns = [
    # path('', views.transaction_index, name='index'),
    path('api/', views.transaction_list),
    path('api/<int:pk>/', views.transaction_detail),
    path('api/history/', views.api_transaction_history),
    path('api/excel/', views.api_transaction_excel),
    path('api/extra/', views.api_transaction_extra, ),


    path('transactions/create_project/<projectpk>', views.transaction_create_project, name='transaction_create_project'),
    path('transactions/update_project/<pk>', views.transaction_update_project, name='transaction_update_project'),
    path('transactions/delete_project/<pk>', views.transaction_delete_project, name='transaction_delete_project'),

    path('transactions/create_project_period/<projectpk>/<periodpk>', views.transaction_create_project_period,
         name='transaction_create_project_period'),
    path('transactions/update_project_period/<pk>/<projectpk>', views.transaction_update_project_period, name='transaction_update_project_period'),
    path('transactions/delete_project_period/<pk>', views.transaction_delete_project_period, name='transaction_delete_project_period'),



    path('ajax/load-purpose/', views.load_purpose, name='ajax_load_purpose'),
    path('ajax/subcontractor-info/', views.subcontractor_info, name='ajax_subcontractor_info'),
    path('ajax/account-info/', views.account_info, name='ajax_account_info'),
    path('ajax/mycompany-info/', views.mycompany_info, name='ajax_mycompany_info'),
    path('ajax/list_saver/', views.list_saver, name='ajax_list_saver'),

    path('transaction_docs/<pk>/', views.transaction_docs, name='transaction_docs'),

    # path('transactions/create/', views.transaction_create, name='transaction_create'),
    # path('transactions/save/', views.transaction_save, name='transaction_save'),
    # path('transactions/update/<pk>', views.transaction_update, name='transaction_update'),
    # path('transactions/delete/<pk>', views.transaction_delete, name='transaction_delete'),

    # path('transfer/create/', views.transfer_create, name='transfer_create'),
    # path('transfer/save/', views.transfer_save, name='transfer_save'),
    # path('transfer/update/<pk>', views.transfer_update, name='transfer_update'),
    # path('transfer/delete/<pk>', views.transfer_delete, name='transfer_delete'),
]

fins/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('app_about.urls')),
    path('app/', include('app_frontend.urls')),
    path('auth/', include('app_auth.urls')),
    path('signup/', include('app_signup.urls')),
    path('setup/', include('app_setup.urls')),
    path('dashboard/', include('app_dashboard.urls')),
    path('projects/', include('app_project.urls')),
    path('transactions/', include('app_transaction.urls')),
    path('docs/', include('app_docs.urls')),
    path('reports/', include('app_reports.urls')),
    path('admin/', admin.site.urls, name='admin'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # import debug_toolbar
    # urlpatterns = [
    #     path('__debug__/', include(debug_toolbar.urls)),
    #
    #     # For django versions before 2.0:
    #     # url(r'^__debug__/', include(debug_toolbar.urls)),
    #
    # ] + urlpatterns

app_project/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from fins.global_functions import IsDeletableMixin, BOOL_CHOICES_YESNO
from simple_history.models import HistoricalRecords
from django.conf import settings
from fins.gist import SpanningForeignKey
from app_signup import models as app_signup_models
from app_transaction import models as app_transaction_models
from app_setup.models import DBUser
from decimal import *
from django.db.models import Case, When, DateField
from app_project.tools_new import statistics

class ProjectCategory(models.Model, IsDeletableMixin):
    name = models.CharField(_('Категория проекта'), max_length=100, unique=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='project_cat_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='project_cat_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('категория проекта')
        verbose_name_plural = _('категории проекта')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class ProjectSubcategory(models.Model, IsDeletableMixin):
    name = models.CharField(_('Субкатегория проекта'), max_length=50, unique=True, blank=True)
    category = models.ForeignKey(ProjectCategory, verbose_name='Категория проекта', related_name="subcategories", on_delete=models.PROTECT, null=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='project_sub_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='project_sub_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('субкатегория проекта')
        verbose_name_plural = _('субкатегории проекта')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class Brand(models.Model, IsDeletableMixin):
    name = models.CharField(_('Бренд'), max_length=100, unique=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='brand_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='brand_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('бренд')
        verbose_name_plural = _('бренды')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class ProductCategory(models.Model, IsDeletableMixin):
    name = models.CharField(_('Категория продукта'), max_length = 50, unique = True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='product_type_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='product_type_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('тип продукта')
        verbose_name_plural = _('типы продукта')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class ProjectProduct(models.Model, IsDeletableMixin):
    name = models.CharField(_('Продукт'), max_length=50, unique=True)
    type = models.ForeignKey(ProductCategory, verbose_name='Категория продукта', on_delete=models.PROTECT, null=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='product_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='product_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('продукт')
        verbose_name_plural = _('продукты')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class NBSource(models.Model, IsDeletableMixin):
    name = models.CharField(_('Источник лида'), max_length=50, unique=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='nbsource_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='nbsource_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('источник привлечения')
        verbose_name_plural = _('источники привлечения')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value

class NBFormat(models.Model, IsDeletableMixin):
    name = models.CharField(_('Формат получения договора'), max_length=50, unique=True, blank=True)

    is_deletable = models.BooleanField(_('Может быть удален'),default=True, choices = BOOL_CHOICES_YESNO)
    created_at = models.DateTimeField(_('Когда создан'), auto_now_add=True)
    created_by = models.ForeignKey(DBUser, related_name='nbformat_created_by', on_delete=models.PROTECT, null=True)
    modified_at = models.DateTimeField(_('Когда изменен'), null=True, blank=True)
    modified_by = models.ForeignKey(DBUser, related_name='nbformat_modified_by', on_delete=models.PROTECT, null=True)
    history = HistoricalRecords(user_model=DBUser)

    class Meta:
        ordering = ['name']
        verbose_name = _('формат получения проекта')
        verbose_name_plural = _('форматы получения проекта')

    def __str__(self):
        return self.name

    @property
    def _history_user(self):
        return self.modified_by

    @_history_user.setter
    def _history_user(self, value):
        self.modified_by = value



class Project(models.Model, IsDeletableMixin):

    WORK_FORMAT_CHOICES = (
        (0, 'Fix'),
        (1, 'Time&Materials'),
    )

    AGREEMENT_FORMAT_CHOICES = (
        (0, 'Договор подряда'),
        (1, 'Агентский договор'),
    )

    STAGES_CHOICES = (
        (0, 'Новый'),
        (1, 'Оценка'),
        (2, 'Продажа'),
        (3, 'Реализация'),
        (4, 'Завершен'),
        (5, 'Не продан'),
    )
    name = models.CharField(_('Номер проекта'), max_length=50)
    name_short = models.CharField(_('Короткое название проекта'), max_length=200)
    name_long = models.CharField(_('Полное название проекта'),max_length=200, blank=True, null=True)
    category = models.ForeignKey(ProjectCategory, verbose_name = 'Категория проекта', related_name="category_projects", on_delete=models.PROTECT, null=True)
    subcategory = models.ForeignKey(ProjectSubcategory, verbose_name = 'Субкатегория проекта', related_name="subcategory_projects" , on_delete=models.PROTECT, null=True, blank=True)

    work_format = models.SmallIntegerField(_('Формат оценки работы'), choices=WORK_FORMAT_CHOICES, default=0)
    agreement_format = models.SmallIntegerField(_('Формат договора'), choices=AGREEMENT_FORMAT_CHOICES, default=0)
    commission = models.SmallIntegerField(_('Агентская комиссия (%)'), blank=True, null=True)
    stage = models.SmallIntegerField(_('Стадия проекта'), choices=STAGES_CHOICES, default=0)

    project_start = models.DateField(_('Начало работы по проекту '),blank=True, null=True)
    project_end = models.DateField(_('Завершение работы по проекту'), blank=True, null=True)

    description = models.CharField(_('Описание проекта'),max_length=10000, blank=True, default='Нет описания')

    estimate_probability = models.IntegerField(_('Вероятность победы'),blank=True, default='0')

app_project/templates/app_project/project_card/partial_linked_docs.html
<small>
    <ul>
        {% for agr in agrs %}

            <li>{{ agr.get_type_display }}  №{{ agr.name }} от {{ agr.signed_at }}</li>
            <ul>
                {% for file in agr.agreement_files.all %}
                    <li><a href="{{file.get_path}}">{{file.get_filename}}</a></li>
                {% endfor %}
            </ul>
            <ul>
                {% for ad in agr.account_docs.all %}
                    <li>{{ ad.get_type_display }}  №{{ ad.name }} от {{ ad.signed_at }}</li>
                    <ul>
                        {% for file in ad.accounting_docs_files.all %}
                            <li><a href="{{file.get_path}}">{{file.get_filename}}</a></li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        {% endfor %}
    </ul>
</small>

    <!--<br>-->
    <!--Первичная документация-->

    <!--<table>-->
        <!--{% for ad in ads %}-->
            <!--<tr>-->
                <!--<td>{{ ad.get_type_display }}  №{{ ad.name }} от {{ ad.signed_at }}</td>-->
            <!--</tr>-->

            <!--{% for file in ad.accounting_docs_files.all %}-->
                <!--<tr>-->
                    <!--<td><a href="{{file.get_path}}">{{file.get_filename}}</a></td>-->
                <!--</tr>-->
            <!--{% endfor %}-->
        <!--{% endfor %}-->

    <!--</table>-->

    <br>

app_project/templates/app_project/project_card/partial_project.html
{% load get_verbose_name %}


<small >
    <div class="row mb-4 text-secondary">
        <div class="col-6">

            <table class="w-100" >
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'category' %}</span></td>
                    <td><span>{{project.category | default_if_none:wording.none}}</span></td>
                </tr>
            </table>
        </div>
        <div class="col-6">
            <table class="w-100" >
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'work_format' %}</span></td>
                    <td><span>{{project.get_work_format_display | default_if_none:wording.none}}</span></td>
                </tr>
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'agreement_format' %}</span></td>
                    <td><span>{{project.get_agreement_format_display | default_if_none:wording.none}}</span></td>
                </tr>
            </table>
        </div>
    </div>

    <hr>

    <div class="row mb-4">
        <div class="col-6">
        <table class="w-100" >
            <tr>
                <td class="py-1"><span>{% get_verbose_name project 'stage' %}</span></td>
                <td><span>{{project.get_stage_display}}</span></td>

            </tr>
            <tr>
                <td class="py-1"><span>{% get_verbose_name project 'name_short' %}</span></td>
                <td><span>{{project.name_short | default:wording.empty_str}}</span></td>
            </tr>
            <tr>
                <td class="py-1"><span>{% get_verbose_name project 'brand' %}</span></td>
                <td><span>{{project.brand | default_if_none:wording.none}}</span></td>
            </tr>
            <tr>
                <td class="py-1"><span>{% get_verbose_name project 'name_long' %}</span></td>
                <td><span>{{project.name_long | default_if_none:wording.none}}</span></td>
            </tr>
            <tr>
                <td class="py-1"><span>{% get_verbose_name project 'subcategory' %}</span></td>
                <td><span>{{project.subcategory | default_if_none:wording.none}}</span></td>
            </tr>
            <tr>
                <td class="py-1"></td>
                <td></td>
            </tr>
        </table>
    </div>
        <div class="col-6">
            <table class="w-100" >
                {% if project.agreement_format == 1 %}
                    <tr class="py-1">
                        <td><span>{% get_verbose_name project 'commission' %}</span></td>
                        <td><span>{{project.commission | default_if_none:wording.none}}</span></td>
                    </tr>
                {% endif %}
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'project_start' %}</span></td>
                    <td><span>{{project.project_start | default_if_none:wording.none}}</span></td>
                </tr>
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'project_end' %}</span></td>
                    <td><span>{{project.project_end | default_if_none:wording.none}}</span></td>
                </tr>
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'nb_source' %}</span></td>
                    <td><span>{{project.nb_source | default_if_none:wording.none}}</span></td>
                </tr>
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'nb_format' %}</span></td>
                    <td><span>{{project.nb_format | default_if_none:wording.none}}</span></td>
                </tr>
                <tr>
                    <td class="py-1"><span>{% get_verbose_name project 'project_products' %}</span></td>
                    <td><span>{{project.products_full | default:wording.empty_str}}</span></td>
                </tr>

            </table>
        </div>
    </div>

    <hr>

    <div  class="row mt-4">
        <div class="col-12">

                <div class="mb-2">
                    <span class="font-weight-bold"> {% get_verbose_name project 'description' %}:</span>
                    <div class="ml-3" style="word-wrap: break-word;"> {{project.description | default:wording.empty_str}}</div>
                </div>

        </div>
    </div>
</small>

app_project/templates/app_project/project_card/partial_project_name.html
#{{project.name}} / {{project.name_short}}

app_project/templates/app_project/project_card/project.html
{% extends 'base_app.html' %}
{% load static %}
{% load widget_tweaks %}
{% load get_verbose_name %}

{% block header %}
    <div style="white-space: nowrap;">
        <div class="d-flex align-items-center">
            <a href="{% url 'app_project:index' %}" class=" px-4 py-4 border-right back-btn"><h4 ><i class="fal fa-chevron-left"></i></h4></a>
            <h1 class="ml-3 mt-1">
                <div id="project_name">{% include 'app_project/project_card/partial_project_name.html' %}</div>
            </h1>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="block-section-3">


    <div id="messages"></div>

    <div class="row mb-5">
        <div class="col-12">
            <h4  class="mb-4">Статистика</h4>
            <table id="statistics" class="table">
                <thead>
                <th>Валюта</th>
                <th>Выручка</th>
                <th>Внешний расход</th>
                <th>Валовая прибыль</th>
                <th>РВП</th>
                </thead>
                <tbody>
                    {% include 'app_project/project_card/partial_statistics.html' %}
                </tbody>
            </table>
        </div>
    </div>




    {% if project.work_format != 1 %}
    <div class="row  mb-5" style="overflow-y: scroll;">
        <div class="col-12">
            <div class="d-flex justify-content-between align-items-start  mb-4">
                <h4 class="mb-3">{{wording.h1_list}}</h4>
                {% if project.is_editable == True or user_can_block == 0 %}
                    <button type="submit" class="js-create-transaction btn btn-sm btn-primary" data-url="{% url 'app_transaction:transaction_create_project' project.pk %}">
                        {{wording.btn_add}}
                    </button>
                {% endif %}

            </div>

            <table id="transactions_list" class="table">
                <thead>
                    {% include 'app_transaction/in_project/partial_list_header.html' %}
                </thead>
                <tbody>
                    {% include 'app_transaction/in_project/partial_list_in_projects.html' %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}



    {% if project.work_format == 1 %}

        <div class="row mb-5  mr-2" style="overflow-y: scroll;">
            <div class="col-12">

                <div class="d-flex justify-content-between align-items-start  mb-4">
                    <h4>{{wording.h1_period}}</h4>
                    {% if project.is_editable == True or user_can_block == 0 %}
                        <button type="submit" class="js-create-period btn  btn-sm btn-primary" data-url="{% url 'app_project:create_period' project.pk %}">
                            {{wording.btn_add2}}
                        </button>
                    {% endif %}
                </div>
                <div id="report_periods">
                    {% include 'app_project/project_card/partial_list_periods.html' %}
                </div>

            </div>
        </div>
    {% endif %}


    <div class="row mb-4 mr-3">
        <div class="col-6" >
            <div class="border mx-1 px-5 py-5 h-100">

                <div class="d-flex justify-content-between align-items-start" >
                    <h4  class="mb-5">Базовые характеристики</h4>
                    {% if project.is_editable == True or user_can_block == 0 %}
                        <button type="button"
                          class="js-update-project btn btn-sm btn-primary mt-1"
                          data-url="{% url 'app_project:project_update' pk %}">
    <!--                        {{wording.btn_update_p}}-->
                            <i class="far fa-pencil"></i>

                        </button>
                    {% endif %}
                </div>
                <div id="partial_project">
                    {% include 'app_project/project_card/partial_project.html' %}
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="border mx-1 px-5 py-5 h-100">

                <div class="d-flex justify-content-between align-items-start">

                    <h4  class="mb-5">Предпродажная оценка</h4>
                    {% if project.is_editable == True or user_can_block == 0 %}
                        <button type="button"
                          class="js-update-estimation-project  btn  btn-sm btn-primary  mt-1"
                          data-url="{% url 'app_project:project_update_estimation' pk %}">
    <!--                        {{wording.btn_est}}-->
                            <i class="far fa-pencil"></i>

                        </button>
                    {% endif %}
                </div>
               <div id="partial_project_estimation">
                    {% include 'app_project/project_card/partial_project_estimation.html' %}
               </div>
            </div>
        </div>
    </div>











    <div class="row mb-4 mr-3">
        {% if project.work_format == 1 %}
                <div class="col-12 ">
                    <div class="border mx-1 px-5 py-5  h-100">
                        <div class="d-flex justify-content-between align-items-start  mb-4">
                            <h4>{{wording.h1_service}}</h4>
                            {% if project.is_editable == True or user_can_block == 0 %}
                                <button type="submit" class="js-create-service btn  btn-sm btn-primary" data-url="{% url 'app_project:service_create' project.pk %}">
                                    <i class="fal fa-plus"></i>
    <!--                                {{wording.btn_add3}}-->
                                </button>
                            {% endif %}
                        </div>
                        <table class="table mb-0">
                            <thead>
                                <th>Название</th>
                                <th>Стоимость часа</th>
                                <th></th>

                            </thead>
                            <tbody id="services">
                                {% include 'app_project/project_card/partial_list_services.html' %}
                            </tbody>
                        </table>
                    </div>
                </div>
        {% endif %}






    </div>


    <div class="row mb-5 mr-3">
        <div class="col-6">
            <div class="border mx-1 px-5 py-5 h-100">

                <div class="d-flex justify-content-between align-items-start mb-4">
                    <h4>Команда</h4>
                    {% if project.is_editable == True or user_can_block == 0 %}
                        <button type="button"
                          class="js-create-team btn btn-sm btn-primary "
                          data-url="{% url 'app_project:team_create' project.pk %}">
                            <i class="fal fa-plus"></i>
    <!--                        {{wording.btn_add5}}-->
                        </button>
                    {% endif %}
                </div>
                <table class="table mb-0">
                    <thead>
                    <th>Пользователь</th>
                    <th>Статус</th>
                    <th></th>
                    </thead>
                    <tbody id="team">
                        {% include 'app_project/project_card/partial_team.html' %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-6">

            <div class="border mx-1 px-5 py-5  h-100">

                <h4 class="mb-4 pb-2">Связанные документы</h4>
                <hr>
                {% if project.project_agreements.all or  project.project_ads.all%}
                    <div >
                        {% include 'app_project/project_card/partial_linked_docs.html' %}
                    </div>
                {% else%}
                    <div>Cвязаный с проектом документов нет</div>
                {% endif %}
            </div>
        </div>
    </div>



    {%  if project.is_deletable == True %}
        {% if project.is_editable == True or user_can_block == 0 %}
            <div class="row mb-5">
                <div class="col-12">
<!--                    <hr>-->
                    <button type="button"
                      class="js-delete-project btn btn-outline-danger mt-4"
                      data-url="{% url 'app_project:project_delete' pk %}">
                        {{wording.btn_delete_p}}
                    </button>
                </div>
            </div>
        {% endif %}
    {% endif %}



</div>


<div class="modal fade" id="modal-global">
    <div class="modal-dialog">
          <div class="modal-content">
         </div>
    </div>
</div>

{% endblock %}



{% block javascript %}
    <script type='text/javascript' src="{% static 'js/projects.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/transactions.js' %}"></script>
{% endblock %}